### ISSUE TITLE
[PE-D][Tester C] Lack of Date Format Hint in Program and Unclear Error Message for Date Input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-2/tp#337]
When entering dates, users may not be aware of the required format (e.g., DD/MM/YYYY or MM-DD-YYYY), as the program does not display this information. If an incorrect date format is entered, the error message does not clarify the expected format, making it challenging for users to correct their input.

![Screenshot 2567-11-08 at 20.51.50.png](https://raw.githubusercontent.com/iamdiluxedbutcooler/ped/main/files/3b014bf9-0ad5-488f-a382-0b2cbb6b4831.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: iamdiluxedbutcooler/ped#29

**Comment by adipanda2002** [comment]
Will need to modify user facing text, so cannot fix this

**Comment by kikokidayo** [comment]
<img width="734" alt="Screenshot 2024-11-11 at 10 01 06 PM" src="https://github.com/user-attachments/assets/6eba4e85-ec87-4fa3-8e70-8c6685631a4a">

Not an issue, the error message shows "Invalid command format" because you did not include the wedding index to edit, if the wedding index is included then the proper date formatting error is shown.
